### ISSUE TITLE
Wave new version of ios9.

### ISSUE THREAD

**Issue by Angelk90** [prscX/react-native-siri-wave-view#1]
@prscX : 
Hi, it would be possible to have the same effect in the images you see below in the new version of ios9.
![screenshot](https://camo.githubusercontent.com/0ae14f367a9ac45d6fd75497b1122101234dcdca/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f662e636c2e6c792f6974656d732f32723269337032473236324d3237314e3046324d2f736972692e676966)
![screenshot](https://s3-us-west-2.amazonaws.com/i.cdpn.io/9590.yfegd.28c789b8-27f2-4ded-985c-f4a5aff295e6.png)

**Comment by prscX** [comment]
Thanks @Angelk90 for raising the request.

Initially I had plans of integrating Siri Wave for iOS 9 as well, but I couldn't find any native library providing the same.

The library which you are referring to is a JS WebView based and we may end up in performance issues. However if you come across any such native library please feel free to raise PR or enhancement request for the same.

Thanks
Pranav

**Comment by k1115** [comment]
Hello
Recently, I've developed native module for iOS 9 Siri Wave.
Could u merge this with yours?

**Comment by prscX** [comment]
Sure, Definitely. Can you please share the link of your module, I will integrate this on priority :smile, I am not able to find in your repositories.

Many Thanks for the module @GreatPotter.

Thanks
Pranav

**Comment by Angelk90** [comment]
Hi @prscX, there have been news about this module on the new version of ios9?

**Comment by prscX** [comment]
Not Yet @Angelk90. Once @GreatPotter publish `iOS 9 Siri` we will integrate the same.

Thanks
Pranav

**Comment by k1115** [comment]
Hi @prscX 
https://github.com/GreatPotter/SiriwaveIOS9
You could see my module there. I used your code basics.

**Comment by prscX** [comment]
Thanks @GreatPotter for sharing the repo.

I have check and it is working as expected. Please find the screenshot below:

<img width="719" alt="screen shot 2018-03-27 at 3 32 13 pm" src="https://user-images.githubusercontent.com/28862892/37960763-1388673a-31d4-11e8-88ef-f3163e4f3bc2.png">
 
Can you please help me in order to understand the source implementation which you have made in order to achieve this:

- Which classes contains your iOS9 wave implementation changes? Is it in [SCSiriWaveformView.m](https://github.com/GreatPotter/SiriwaveIOS9/blob/master/ios/SCSiriWaveformView/SCSiriWaveformView.m) or [SiriWaveCurve.m](https://github.com/GreatPotter/SiriwaveIOS9/blob/master/ios/SiriWaveCurve.m) class?

- Are you planning to open source native iOS 9 wave implementation? or should I go forward and open source both?

Thanks
Pranav

**Comment by GreatPotter** [comment]
I've changed main module you used.

**Comment by k1115** [comment]
I modified SCSiriWaveformView.m file and added
SiriWaveCurve.m, SiriWaveCurve.h files

**Comment by prscX** [comment]
@GreatPotter: So should I integrate those changes in this library? If so we can plan to Open Source two libraries:

- Native iOS 9 Siri Wave
- Integrate Native iOS 9 Siri Wave into this library.

Please let me know your thoughts about the same.

Thanks
Pranav

**Comment by k1115** [comment]
Yes, I used Open Source Native libraries and added custom functionality.

**Comment by prscX** [comment]
Hi @GreatPotter, Can you please provide the list of Open Source libraries which you have used in order to achieve this.

Thanks
Pranav

**Comment by k1115** [comment]
I used the same library as you used.

**Comment by prscX** [comment]
@GreatPotter: So the same library you have modified in order to achieve this? If so can I Open Source it by crediting it on your name?

Thanks
Pranav

**Comment by k1115** [comment]
Sure.

**Comment by prscX** [comment]
Thanks @GreatPotter.

Thanks
Pranav

**Comment by k1115** [comment]
Thanks
Maik

**Comment by prscX** [comment]
Hi @GreatPotter, 

Many Thanks for the Siri Waveform 9 Implementation, I have integrated your implementation with this library. Now you will be able to use it by providing `type` prop as `1`. 

Hi @Angelk90,

With the help of @GreatPotter, I have enabled support for iOS Siri Wave 9. In order to use please install latest version `0.0.4` for the same.

[V0.0.4](https://github.com/prscX/react-native-siri-wave-view/releases/tag/v0.0.4)

Please let me know in case you face any issues.

Thanks
Pranav

**Comment by k1115** [comment]
Hi @prscX 

I hope collaborate with you at any time.

Thanks.
Maik

**Comment by prscX** [comment]
Definitely @GreatPotter :smile. Please feel free to reach at any time.

Thanks
Pranav

**Comment by k1115** [comment]
Hi @prscX 
It's great to see you again. 
Recently, I changed my account name to k1115.
Could you change GreatPotter to k1115 on readme, please?
